
-- genre table 

--select * from genre;

insert into genre values(1,'Rock')
insert into genre values(2,'Jazz')
insert into genre values(3,'Metal')
insert into genre values(4,'Alternative & Punk')
insert into genre values(5,'Rock And Roll')
insert into genre values(6,'Blues')
insert into genre values(7,'Latin')
insert into genre values(8,'Reggae')
insert into genre values(9,'Pop')
insert into genre values(10,'Soundtrack')
insert into genre values(11,'Bossa Nova')
insert into genre values(12,'Easy Listening')
insert into genre values(13,'Heavy Metal')
insert into genre values(14,'R&B/Soul')
insert into genre values(15,'Electronica/Dance')
insert into genre values(16,'World')
insert into genre values(17,'Hip Hop/Rap')
insert into genre values(18,'Science Fiction')
insert into genre values(19,'TV Shows')
insert into genre values(20,'Sci Fi & Fantasy')
insert into genre values(21,'Drama')
insert into genre values(22,'Comedy')
insert into genre values(23,'Alternative')
insert into genre values(24,'Classical')
insert into genre values(25,'Opera')
