

--artist tab

select * from artist

insert into artist values(1,'AC/DC')
insert into artist values(2,'Accept')
insert into artist values(3,'Aerosmith')
insert into artist values(4,'Alanis Morissette')
insert into artist values(5,'Alice In Chains')
insert into artist values(6,'Ant��nio Carlos Jobim')
insert into artist values(7,'Apocalyptica')
insert into artist values(8,'Audioslave')
insert into artist values(9,'BackBeat')
insert into artist values(10,'Billy Cobham')
insert into artist values(11,'Black Label Society')
insert into artist values(12,'Black Sabbath')
insert into artist values(13,'Body Count')
insert into artist values(14,'Bruce Dickinson')
insert into artist values(15,'Buddy Guy')
insert into artist values(16,'Caetano Veloso')
insert into artist values(17,'Chico Buarque')
insert into artist values(18,'Chico Science & Na����o Zumbi')
insert into artist values(19,'Cidade Negra')
insert into artist values(20,'Cl��udio Zoli')
insert into artist values(21,'Various Artists')
insert into artist values(22,'Led Zeppelin')
insert into artist values(23,'Frank Zappa & Captain Beefheart')
insert into artist values(24,'Marcos Valle')
insert into artist values(25,'Milton Nascimento & Bebeto')
insert into artist values(26,'Azymuth')
insert into artist values(27,'Gilberto Gil')
insert into artist values(28,'Jo��o Gilberto')
insert into artist values(29,'Bebel Gilberto')
insert into artist values(30,'Jorge Vercilo')
insert into artist values(31,'Baby Consuelo')
insert into artist values(32,'Ney Matogrosso')
insert into artist values(33,'Luiz Melodia')
insert into artist values(34,'Nando Reis')
insert into artist values(35,'Pedro Lu��s & A Parede')
insert into artist values(36,'O Rappa')
insert into artist values(37,'Ed Motta')
insert into artist values(38,'Banda Black Rio')
insert into artist values(39,'Fernanda Porto')
insert into artist values(40,'Os Cariocas')
insert into artist values(41,'Elis Regina')
insert into artist values(42,'Milton Nascimento')
insert into artist values(43,'A Cor Do Som')
insert into artist values(44,'Kid Abelha')
insert into artist values(45,'Sandra De S��')
insert into artist values(46,'Jorge Ben')
insert into artist values(47,'Hermeto Pascoal')
insert into artist values(48,'Bar��o Vermelho')
insert into artist values(49,'Edson, DJ Marky & DJ Patife Featuring Fernanda Porto')
insert into artist values(50,'Metallica')
insert into artist values(51,'Queen')
insert into artist values(52,'Kiss')
insert into artist values(53,'Spyro Gyra')
insert into artist values(54,'Green Day')
insert into artist values(55,'David Coverdale')
insert into artist values(56,'Gonzaguinha')
insert into artist values(57,'Os Mutantes')
insert into artist values(58,'Deep Purple')
insert into artist values(59,'Santana')
insert into artist values(60,'Santana Feat. Dave Matthews')
insert into artist values(61,'Santana Feat. Everlast')
insert into artist values(62,'Santana Feat. Rob Thomas')
insert into artist values(63,'Santana Feat. Lauryn Hill & Cee-Lo')
insert into artist values(64,'Santana Feat. The Project G&B')
insert into artist values(65,'Santana Feat. Man��')
insert into artist values(66,'Santana Feat. Eagle-Eye Cherry')
insert into artist values(67,'Santana Feat. Eric Clapton')
insert into artist values(68,'Miles Davis')
insert into artist values(69,'Gene Krupa')
insert into artist values(70,'Toquinho & Vin��cius')
insert into artist values(71,'Vin��cius De Moraes & Baden Powell')
insert into artist values(72,'Vin��cius De Moraes')
insert into artist values(73,'Vin��cius E Qurteto Em Cy')
insert into artist values(74,'Vin��cius E Odette Lara')
insert into artist values(75,'Vinicius, Toquinho & Quarteto Em Cy')
insert into artist values(76,'Creedence Clearwater Revival')
insert into artist values(77,'C��ssia Eller')
insert into artist values(78,'Def Leppard')
insert into artist values(79,'Dennis Chambers')
insert into artist values(80,'Djavan')
insert into artist values(81,'Eric Clapton')
insert into artist values(82,'Faith No More')
insert into artist values(83,'Falamansa')
insert into artist values(84,'Foo Fighters')
insert into artist values(85,'Frank Sinatra')
insert into artist values(86,'Funk Como Le Gusta')
insert into artist values(87,'Godsmack')
insert into artist values(88,'Guns N Roses')
insert into artist values(89,'Incognito')
insert into artist values(90,'Iron Maiden')
insert into artist values(91,'James Brown')
insert into artist values(92,'Jamiroquai')
insert into artist values(93,'JET')
insert into artist values(94,'Jimi Hendrix')
insert into artist values(95,'Joe Satriani')
insert into artist values(96,'Jota Quest')
insert into artist values(97,'Jo��o Suplicy')
insert into artist values(98,'Judas Priest')
insert into artist values(99,'Legi��o Urbana')
insert into artist values(100,'Lenny Kravitz')
insert into artist values(101,'Lulu Santos')
insert into artist values(102,'Marillion')
insert into artist values(103,'Marisa Monte')
insert into artist values(104,'Marvin Gaye')
insert into artist values(105,'Men At Work')
insert into artist values(106,'Mot��rhead')
insert into artist values(107,'Mot��rhead & Girlschool')
insert into artist values(108,'M��nica Marianno')
insert into artist values(109,'M��tley Cr��e')
insert into artist values(110,'Nirvana')
insert into artist values(111,'O Ter��o')
insert into artist values(112,'Olodum')
insert into artist values(113,'Os Paralamas Do Sucesso')
insert into artist values(114,'Ozzy Osbourne')
insert into artist values(115,'Page & Plant')
insert into artist values(116,'Passengers')
insert into artist values(117,'Paul D Ianno')
insert into artist values(118,'Pearl Jam')
insert into artist values(119,'Peter Tosh')
insert into artist values(120,'Pink Floyd')
insert into artist values(121,'Planet Hemp')
insert into artist values(122,'R.E.M. Feat. Kate Pearson')
insert into artist values(123,'R.E.M. Feat. KRS-One')
insert into artist values(124,'R.E.M.')
insert into artist values(125,'Raimundos')
insert into artist values(126,'Raul Seixas')
insert into artist values(127,'Red Hot Chili Peppers')
insert into artist values(128,'Rush')
insert into artist values(129,'Simply Red')
insert into artist values(130,'Skank')
insert into artist values(131,'Smashing Pumpkins')
insert into artist values(132,'Soundgarden')
insert into artist values(133,'Stevie Ray Vaughan & Double Trouble')
insert into artist values(134,'Stone Temple Pilots')
insert into artist values(135,'System Of A Down')
insert into artist values(136,'Terry Bozzio, Tony Levin & Steve Stevens')
insert into artist values(137,'The Black Crowes')
insert into artist values(138,'The Clash')
insert into artist values(139,'The Cult')
insert into artist values(140,'The Doors')
insert into artist values(141,'The Police')
insert into artist values(142,'The Rolling Stones')
insert into artist values(143,'The Tea Party')
insert into artist values(144,'The Who')
insert into artist values(145,'Tim Maia')
insert into artist values(146,'Tit��s')
insert into artist values(147,'Battlestar Galactica')
insert into artist values(148,'Heroes')
insert into artist values(149,'Lost')
insert into artist values(150,'U2')
insert into artist values(151,'UB40')
insert into artist values(152,'Van Halen')
insert into artist values(153,'Velvet Revolver')
insert into artist values(154,'Whitesnake')
insert into artist values(155,'Zeca Pagodinho')
insert into artist values(156,'The Office')
insert into artist values(157,'Dread Zeppelin')
insert into artist values(158,'Battlestar Galactica (Classic)')
insert into artist values(159,'Aquaman')
insert into artist values(160,'Christina Aguilera featuring BigElf')
insert into artist values(161,'Aerosmith & Sierra Leones Refugee Allstars')
insert into artist values(162,'Los Lonely Boys')
insert into artist values(163,'Corinne Bailey Rae')
insert into artist values(164,'Dhani Harrison & Jakob Dylan')
insert into artist values(165,'Jackson Browne')
insert into artist values(166,'Avril Lavigne')
insert into artist values(167,'Big & Rich')
insert into artist values(168,'Youssou N Dour')
insert into artist values(169,'Black Eyed Peas')
insert into artist values(170,'Jack Johnson')
insert into artist values(171,'Ben Harper')
insert into artist values(172,'Snow Patrol')
insert into artist values(173,'Matisyahu')
insert into artist values(174,'The Postal Service')
insert into artist values(175,'Jaguares')
insert into artist values(176,'The Flaming Lips')
insert into artist values(177,'Jacks Mannequin & Mick Fleetwood')
insert into artist values(178,'Regina Spektor')
insert into artist values(179,'Scorpions')
insert into artist values(180,'House Of Pain')
insert into artist values(181,'Xis')
insert into artist values(182,'Nega Gizza')
insert into artist values(183,'Gustavo & Andres Veiga & Salazar')
insert into artist values(184,'Rodox')
insert into artist values(185,'Charlie Brown Jr.')
insert into artist values(186,'Pedro Lu��s E A Parede')
insert into artist values(187,'Los Hermanos')
insert into artist values(188,'Mundo Livre S/A')
insert into artist values(189,'Otto')
insert into artist values(190,'Instituto')
insert into artist values(191,'Na����o Zumbi')
insert into artist values(192,'DJ Dolores & Orchestra Santa Massa')
insert into artist values(193,'Seu Jorge')
insert into artist values(194,'Sabotage E Instituto')
insert into artist values(195,'Stereo Maracana')
insert into artist values(196,'Cake')
insert into artist values(197,'Aisha Duo')
insert into artist values(198,'Habib Koit�� and Bamada')
insert into artist values(199,'Karsh Kale')
insert into artist values(200,'The Posies')
insert into artist values(201,'Luciana Souza/Romero Lubambo')
insert into artist values(202,'Aaron Goldberg')
insert into artist values(203,'Nicolaus Esterhazy Sinfonia')
insert into artist values(204,'Temple of the Dog')
insert into artist values(205,'Chris Cornell')
insert into artist values(206,'Alberto Turco & Nova Schola Gregoriana')
insert into artist values(207,'Richard Marlow & The Choir of Trinity College, Cambridge')
insert into artist values(208,'English Concert & Trevor Pinnock')
insert into artist values(209,'Anne-Sophie Mutter, Herbert Von Karajan & Wiener Philharmoniker')
insert into artist values(210,'Hilary Hahn, Jeffrey Kahane, Los Angeles Chamber Orchestra & Margaret Batjer')
insert into artist values(211,'Wilhelm Kempff')
insert into artist values(212,'Yo-Yo Ma')
insert into artist values(213,'Scholars Baroque Ensemble')
insert into artist values(214,'Academy of St. Martin in the Fields & Sir Neville Marriner')
insert into artist values(215,'Academy of St. Martin in the Fields Chamber Ensemble & Sir Neville Marriner')
insert into artist values(216,'Berliner Philharmoniker, Claudio Abbado & Sabine Meyer')
insert into artist values(217,'Royal Philharmonic Orchestra & Sir Thomas Beecham')
insert into artist values(218,'Orchestre R��volutionnaire et Romantique & John Eliot Gardiner')
insert into artist values(219,'Britten Sinfonia, Ivor Bolton & Lesley Garrett')
insert into artist values(220,'Chicago Symphony Chorus, Chicago Symphony Orchestra & Sir Georg Solti')
insert into artist values(221,'Sir Georg Solti & Wiener Philharmoniker')
insert into artist values(222,'Academy of St. Martin in the Fields, John Birch, Sir Neville Marriner & Sylvia McNair')
insert into artist values(223,'London Symphony Orchestra & Sir Charles Mackerras')
insert into artist values(224,'Barry Wordsworth & BBC Concert Orchestra')
insert into artist values(225,'Herbert Von Karajan, Mirella Freni & Wiener Philharmoniker')
insert into artist values(226,'Eugene Ormandy')
insert into artist values(227,'Luciano Pavarotti')
insert into artist values(228,'Leonard Bernstein & New York Philharmonic')
insert into artist values(229,'Boston Symphony Orchestra & Seiji Ozawa')
insert into artist values(230,'Aaron Copland & London Symphony Orchestra')
insert into artist values(231,'Ton Koopman')
insert into artist values(232,'Sergei Prokofiev & Yuri Temirkanov')
insert into artist values(233,'Chicago Symphony Orchestra & Fritz Reiner')
insert into artist values(234,'Orchestra of The Age of Enlightenment')
insert into artist values(235,'Emanuel Ax, Eugene Ormandy & Philadelphia Orchestra')
insert into artist values(236,'James Levine')
insert into artist values(237,'Berliner Philharmoniker & Hans Rosbaud')
insert into artist values(238,'Maurizio Pollini')
insert into artist values(239,'Academy of St. Martin in the Fields, Sir Neville Marriner & William Bennett')
insert into artist values(240,'Gustav Mahler')
insert into artist values(241,'Felix Schmidt, London Symphony Orchestra & Rafael Fr��hbeck de Burgos')
insert into artist values(242,'Edo de Waart & San Francisco Symphony')
insert into artist values(243,'Antal Dor��ti & London Symphony Orchestra')
insert into artist values(244,'Choir Of Westminster Abbey & Simon Preston')
insert into artist values(245,'Michael Tilson Thomas & San Francisco Symphony')
insert into artist values(246,'Chor der Wiener Staatsoper, Herbert Von Karajan & Wiener Philharmoniker')
insert into artist values(247,'The Kings Singers')
insert into artist values(248,'Berliner Philharmoniker & Herbert Von Karajan')
insert into artist values(249,'Sir Georg Solti, Sumi Jo & Wiener Philharmoniker') ;
insert into artist values(250,'Christopher O Riley')
insert into artist values(251,'Fretwork')
insert into artist values(252,'Amy Winehouse')
insert into artist values(253,'Calexico')
insert into artist values(254,'Otto Klemperer & Philharmonia Orchestra')
insert into artist values(255,'Yehudi Menuhin')
insert into artist values(256,'Philharmonia Orchestra & Sir Neville Marriner')
insert into artist values(257,'Academy of St. Martin in the Fields, Sir Neville Marriner & Thurston Dart')
insert into artist values(258,'Les Arts Florissants & William Christie')
insert into artist values(259,'The 12 Cellists of The Berlin Philharmonic')
insert into artist values(260,'Adrian Leaper & Doreen de Feis')
insert into artist values(261,'Roger Norrington, London Classical Players')
insert into artist values(262,'Charles Dutoit & L Orchestre Symphonique de Montr��al')
insert into artist values(263,'Equale Brass Ensemble, John Eliot Gardiner & Munich Monteverdi Orchestra and Choir')
insert into artist values(264,'Kent Nagano and Orchestre de l Op��ra de Lyon')
insert into artist values(265,'Julian Bream')
insert into artist values(266,'Martin Roscoe')
insert into artist values(267,'G��teborgs Symfoniker & Neeme J��rvi')
insert into artist values(268,'Itzhak Perlman')
insert into artist values(269,'Michele Campanella')
insert into artist values(270,'Gerald Moore')
insert into artist values(271,'Mela Tenenbaum, Pro Musica Prague & Richard Kapp')
insert into artist values(272,'Emerson String Quartet')
insert into artist values(273,'C. Monteverdi, Nigel Rogers - Chiaroscuro; London Baroque; London Cornett & Sackbu')
insert into artist values(274,'Nash Ensemble')
insert into artist values(275,'Philip Glass Ensemble')


