
-- album tab


insert into album values(1,'For Those About To Rock We Salute You',1)
insert into album values(2,'Balls to the Wall',2)
insert into album values(3,'Restless and Wild',2)
insert into album values(4,'Let There Be Rock',1)
insert into album values(5,'Big Ones',3)
insert into album values(6,'Jagged Little Pill',4)
insert into album values(7,'Facelift',5)
insert into album values(8,'Warner 25 Anos',6)
insert into album values(9,'Plays Metallica By Four Cellos',7)
insert into album values(10,'Audioslave',8)
insert into album values(11,'Out Of Exile',8)
insert into album values(12,'BackBeat Soundtrack',9)
insert into album values(13,'The Best Of Billy Cobham',10)
insert into album values(14,'Alcohol Fueled Brewtality Live! [Disc 1]',11)
insert into album values(15,'Alcohol Fueled Brewtality Live! [Disc 2]',11)
insert into album values(16,'Black Sabbath',12)
insert into album values(17,'Black Sabbath Vol. 4 (Remaster)',12)
insert into album values(18,'Body Count',13)
insert into album values(19,'Chemical Wedding',14)
insert into album values(20,'The Best Of Buddy Guy - The Millenium Collection',15)
insert into album values(21,'Prenda Minha',16)
insert into album values(22,'Sozinho Remix Ao Vivo',16)
insert into album values(23,'Minha Historia',17)
insert into album values(24,'Afrociberdelia',18)
insert into album values(25,'Da Lama Ao Caos',18)
insert into album values(26,'Acastico MTV live',19)
insert into album values(27,'Cidade Negra - Hits',19)
insert into album values(28,'Na Pista',20)
insert into album values(29,'AxA Bahia 2001',21)
insert into album values(30,'BBC Sessions [Disc 1] [live]',22)
insert into album values(31,'Bongo Fury',23)
insert into album values(32,'Carnaval 2001',21)
insert into album values(33,'Chill: Brazil (Disc 1)',24)
insert into album values(34,'Chill: Brazil (Disc 2)',6)
insert into album values(35,'Garage Inc. (Disc 1)',50)
insert into album values(36,'Greatest Hits II',51)
insert into album values(37,'Greatest Kiss',52)
insert into album values(38,'Heart of the Night',53)
insert into album values(39,'International Superhits',54)
insert into album values(40,'Into The Light',55)
insert into album values(41,'Meus Momentos',56)
insert into album values(42,'Minha HistÃ³ria',57)
insert into album values(43,'MK III The Final Concerts [Disc 1]',58)
insert into album values(44,'Physical Graffiti [Disc 1]',22)
insert into album values(45,'Sambas De Enredo 2001',21)
insert into album values(46,'Supernatural',59)
insert into album values(47,'The Best of Ed Motta',37)
insert into album values(48,'The Essential Miles Davis [Disc 1]',68)
insert into album values(49,'The Essential Miles Davis [Disc 2]',68)
insert into album values(50,'The Final Concerts (Disc 2)',58)
insert into album values(51,'Up An  Atom',69)
insert into album values(52,'VinÃ­cius De Moraes - Sem Limite',70)
insert into album values(53,'Vozes do MPB',21)
insert into album values(54,'Chronicle, Vol. 1',76)
insert into album values(55,'Chronicle, Vol. 2',76)
insert into album values(56,'CÃ¡ssia Eller - ColeÃ§Ã£o Sem Limite [Disc 2]',77)
insert into album values(57,'CÃ¡ssia Eller - Sem Limite [Disc 1]',77)
insert into album values(58,'Come Taste The Band',58)
insert into album values(59,'Deep Purple In Rock',58)
insert into album values(60,'Fireball',58)
insert into album values(61,'Knocking at Your Back Door: The Best Of Deep Purple in the 80 s',58)
insert into album values(62,'Machine Head',58)
insert into album values(63,'Purpendicular',58)
insert into album values(64,'Slaves And Masters',58)
insert into album values(65,'Stormbringer',58)
insert into album values(66,'The Battle Rages On',58)
insert into album values(67,'Vault: Def Leppard s Greatest Hits',78)
insert into album values(68,'Outbreak',79)
insert into album values(69,'Djavan Ao Vivo - Vol. 02',80)
insert into album values(70,'Djavan Ao Vivo - Vol. 1',80)
insert into album values(71,'Elis Regina-Minha HistÃ³ria',41)
insert into album values(72,'The Cream Of Clapton',81)
insert into album values(73,'Unplugged',81)
insert into album values(74,'Album Of The Year',82)
insert into album values(75,'Angel Dust',82)
insert into album values(76,'King For A Day Fool For A Lifetime',82)
insert into album values(77,'The Real Thing',82)
insert into album values(78,'Deixa Entrar',83)
insert into album values(79,'In Your Honor [Disc 1]',84)
insert into album values(80,'In Your Honor [Disc 2]',84)
insert into album values(81,'One By One',84)
insert into album values(82,'The Colour And The Shape',84)
insert into album values(83,'My Way: The Best Of Frank Sinatra [Disc 1]',85)
insert into album values(84,'Roda De Funk',86)
insert into album values(85,'As CanÃ§Ãµes de Eu Tu Eles',27)
insert into album values(86,'Quanta Gente Veio Ver (Live)',27)
insert into album values(87,'Quanta Gente Veio ver--BÃ´nus De Carnaval',27)
insert into album values(88,'Faceless',87)
insert into album values(89,'American Idiot',54)
insert into album values(90,'Appetite for Destruction',88)
insert into album values(91,'Use Your Illusion I',88)
insert into album values(92,'Use Your Illusion II',88)
insert into album values(93,'Blue Moods',89)
insert into album values(94,'A Matter of Life and Death',90)
insert into album values(95,'A Real Dead One',90)
insert into album values(96,'A Real Live One',90)
insert into album values(97,'Brave New World',90)
insert into album values(98,'Dance Of Death',90)
insert into album values(99,'Fear Of The Dark',90)
insert into album values(100,'Iron Maiden',90)
insert into album values(101,'Killers',90)
insert into album values(102,'Live After Death',90)
insert into album values(103,'Live At Donington 1992 (Disc 1)',90)
insert into album values(104,'Live At Donington 1992 (Disc 2)',90)
insert into album values(105,'No Prayer For The Dying',90)
insert into album values(106,'Piece Of Mind',90)
insert into album values(107,'Powerslave',90)
insert into album values(108,'Rock In Rio [cd1]',90)
insert into album values(109,'Rock In Rio [cd2]',90)
insert into album values(110,'Seventh Son of a Seventh Son',90)
insert into album values(111,'Somewhere in Time',90)
insert into album values(112,'The Number of The Beast',90)
insert into album values(113,'The X Factor',90)
insert into album values(114,'Virtual XI',90)
insert into album values(115,'Sex Machine',91)
insert into album values(116,'Emergency On Planet Earth',92)
insert into album values(117,'Synkronized',92)
insert into album values(118,'The Return Of The Space Cowboy',92)
insert into album values(119,'Get Born',93)
insert into album values(120,'Are You Experienced?',94)
insert into album values(121,'Surfing with the Alien (Remastered)',95)
insert into album values(122,'Jorge Ben Jor 25 Anos',46)
insert into album values(123,'Jota Quest-1995',96)
insert into album values(124,'Cafezinho',97)
insert into album values(125,'Living After Midnight',98)
insert into album values(126,'Unplugged [live]',52)
insert into album values(127,'BBC Sessions [Disc 2] [live]',22)
insert into album values(128,'Coda',22)
insert into album values(129,'Houses Of The Holy',22)
insert into album values(130,'In Through The Out Door',22)
insert into album values(131,'IV',22)
insert into album values(132,'Led Zeppelin I',22)
insert into album values(133,'Led Zeppelin II',22)
insert into album values(134,'Led Zeppelin III',22)
insert into album values(135,'Physical Graffiti [Disc 2]',22)
insert into album values(136,'Presence',22)
insert into album values(137,'The Song Remains The Same (Disc 1)',22)
insert into album values(138,'The Song Remains The Same (Disc 2)',22)
insert into album values(139,'A TempestadeTempestade Ou O Livro Dos Dias',99)
insert into album values(140,'Mais Do Mesmo',99)
insert into album values(141,'Greatest Hits',100)
insert into album values(142,'Lulu Santos - RCA 100 Anos De MÃºsica - Ãlbum 01',101)
insert into album values(143,'Lulu Santos - RCA 100 Anos De MÃºsica - Ãlbum 02',101)
insert into album values(144,'Misplaced Childhood',102)
insert into album values(145,'Barulhinho Bom',103)
insert into album values(146,'Seek And Shall Find: More Of The Best (1963-1981)',104)
insert into album values(147,'The Best Of Men At Work',105)
insert into album values(148,'Black Album',50)
insert into album values(149,'Garage Inc. (Disc 2)',50)
insert into album values(150,'Kill  Em All',50)
insert into album values(151,'Load',50)
insert into album values(152,'Master Of Puppets',50)
insert into album values(153,'ReLoad',50)
insert into album values(154,'Ride The Lightning',50)
insert into album values(155,'St. Anger',50)
insert into album values(156,'And Justice For All',50)
insert into album values(157,'Miles Ahead',68)
insert into album values(158,'Milton Nascimento Ao Vivo',42)
insert into album values(159,'Minas',42)
insert into album values(160,'Ace Of Spades',106)
insert into album values(161,'Demorou...',108)
insert into album values(162,'Motley Crue Greatest Hits',109)
insert into album values(163,'From The Muddy Banks Of The Wishkah [live]',110)
insert into album values(164,'Nevermind',110)
insert into album values(165,'Compositores',111)
insert into album values(166,'Olodum',112)
insert into album values(167,'Acastico MTV',113)
insert into album values(168,'Arquivo II',113)
insert into album values(169,'Arquivo Os Paralamas Do Sucesso',113)
insert into album values(170,'Bark at the Moon (Remastered)',114)
insert into album values(171,'Blizzard of Ozz',114)
insert into album values(172,'Diary of a Madman (Remastered)',114)
insert into album values(173,'No More Tears (Remastered)',114)
insert into album values(174,'Tribute',114)
insert into album values(175,'Walking Into Clarksdale',115)
insert into album values(176,'Original Soundtracks 1',116)
insert into album values(177,'The Beast Live',117)
insert into album values(178,'Live On Two Legs [live]',118)
insert into album values(179,'Pearl Jam',118)
insert into album values(180,'Riot Act',118)
insert into album values(181,'Ten',118)
insert into album values(182,'Vs.',118)
insert into album values(183,'Dark Side Of The Moon',120)
insert into album values(184,'Os CÃ£es Ladram Mas A Caravana NÃ£o PÃ¡ra',121)
insert into album values(185,'Greatest Hits I',51)
insert into album values(186,'News Of The World',51)
insert into album values(187,'Out Of Time',122)
insert into album values(188,'Green',124)
insert into album values(189,'New Adventures In Hi-Fi',124)
insert into album values(190,'The Best Of R.E.M.: The IRS Years',124)
insert into album values(191,'Cesta BÃ¡sica',125)
insert into album values(192,'Raul Seixas',126)
insert into album values(193,'Blood Sugar Sex Magik',127)
insert into album values(194,'By The Way',127)
insert into album values(195,'Californication',127)
insert into album values(196,'Retrospective I (1974-1980)',128)
insert into album values(197,'Santana - As Years Go By',59)
insert into album values(198,'Santana Live',59)
insert into album values(199,'Maquinarama',130)
insert into album values(200,'O Samba PoconÃ©',130)
insert into album values(201,'Judas 0: B-Sides and Rarities',131)
insert into album values(202,'Rotten Apples: Greatest Hits',131)
insert into album values(203,'A-Sides',132)
insert into album values(204,'Morning Dance',53)
insert into album values(205,'In Step',133)
insert into album values(206,'Core',134)
insert into album values(207,'Mezmerize',135)
insert into album values(208,'Black Light Syndrome',136)
insert into album values(209,'Live [Disc 1]',137)
insert into album values(210,'Live [Disc 2]',137)
insert into album values(211,'The Singles',138)
insert into album values(212,'Beyond Good And Evil',139)
insert into album values(213,'Pure Cult: The Best Of The Cult (For Rockers, Ravers, Lovers & Sinners) [uk]',139)
insert into album values(214,'The Doors',140)
insert into album values(215,'The Police Greatest Hits',141)
insert into album values(216,'Hot Rocks, 1964-1971 (Disc 1)',142)
insert into album values(217,'No Security',142)
insert into album values(218,'Voodoo Lounge',142)
insert into album values(219,'Tangents',143)
insert into album values(220,'Transmission',143)
insert into album values(221,'My Generation - The Very Best Of The Who',144)
insert into album values(222,'Serie Sem Limite (Disc 1)',145)
insert into album values(223,'Serie Sem Limite (Disc 2)',145)
insert into album values(224,'Acastico',146)
insert into album values(225,'Volume Dois',146)
insert into album values(226,'Battlestar Galactica: The Story So Far',147)
insert into album values(227,'Battlestar Galactica, Season 3',147)
insert into album values(228,'Heroes, Season 1',148)
insert into album values(229,'Lost, Season 3',149)
insert into album values(230,'Lost, Season 1',149)
insert into album values(231,'Lost, Season 2',149)
insert into album values(232,'Achtung Baby',150)
insert into album values(233,'All That You Can t Leave Behind',150)
insert into album values(234,'B-Sides 1980-1990',150)
insert into album values(235,'How To Dismantle An Atomic Bomb',150)
insert into album values(236,'Pop',150)
insert into album values(237,'Rattle And Hum',150)
insert into album values(238,'The Best Of 1980-1990',150)
insert into album values(239,'War',150)
insert into album values(240,'Zooropa',150)
insert into album values(241,'UB40 The Best Of - Volume Two [uk]',151)
insert into album values(242,'Diver Down',152)
insert into album values(243,'The Best Of Van Halen, Vol. I',152)
insert into album values(244,'Van Halen',152)
insert into album values(245,'Van Halen III',152)
insert into album values(246,'Contraband',153)
insert into album values(247,'Vinicius De Moraes',72)
insert into album values(248,'Ao Vivo [import]',155)
insert into album values(249,'The Office, Season 1',156)
insert into album values(250,'The Office, Season 2',156)
insert into album values(251,'The Office, Season 3',156)
insert into album values(252,'Un-Led-Ed',157)
insert into album values(253,'Battlestar Galactica (Classic), Season 1',158)
insert into album values(254,'Aquaman',159)
insert into album values(255,'Instant Karma: The Amnesty International Campaign to Save Darfur',150)
insert into album values(256,'Speak of the Devil',114)
insert into album values(257,'20th Century Masters - The Millennium Collection: The Best of Scorpions',179)
insert into album values(258,'House of Pain',180)
insert into album values(259,'Radio Brasil (O Som da Jovem Vanguarda) - Seleccao de Henrique Amaro',36)
insert into album values(260,'Cake: B-Sides and Rarities',196)
insert into album values(261,'LOST, Season 4',149)
insert into album values(262,'Quiet Songs',197)
insert into album values(263,'Muso Ko',198)
insert into album values(264,'Realize',199)
insert into album values(265,'Every Kind of Light',200)
insert into album values(266,'Duos II',201)
insert into album values(267,'Worlds',202)
insert into album values(268,'The Best of Beethoven',203)
insert into album values(269,'Temple of the Dog',204)
insert into album values(270,'Carry On',205)
insert into album values(271,'Revelations',8)
insert into album values(272,'Adorate Deum: Gregorian Chant from the Proper of the Mass',206)
insert into album values(273,'Allegri: Miserere',207)
insert into album values(274,'Pachelbel: Canon & Gigue',208)
insert into album values(275,'Vivaldi: The Four Seasons',209)
insert into album values(276,'Bach: Violin Concertos',210)
insert into album values(277,'Bach: Goldberg Variations',211)
insert into album values(278,'Bach: The Cello Suites',212)
insert into album values(279,'Handel: The Messiah (Highlights)',213)
insert into album values(280,'The World of Classical Favourites',214)
insert into album values(281,'Sir Neville Marriner: A Celebration',215)
insert into album values(282,'Mozart: Wind Concertos',216)
insert into album values(283,'Haydn: Symphonies 99 - 104',217)
insert into album values(284,'Beethoven: Symhonies Nos. 5 & 6',218)
insert into album values(285,'A Soprano Inspired',219)
insert into album values(286,'Great Opera Choruses',220)
insert into album values(287,'Wagner: Favourite Overtures',221)
insert into album values(288,'FaurÃ©: Requiem, Ravel: Pavane & Others',222)
insert into album values(289,'Tchaikovsky: The Nutcracker',223)
insert into album values(290,'The Last Night of the Proms',224)
insert into album values(291,'Puccini: Madama Butterfly - Highlights',225)
insert into album values(292,'Holst: The Planets, Op. 32 & Vaughan Williams: Fantasies',226)
insert into album values(293,'Pavarotti s Opera Made Easy',227)
insert into album values(294,'Great Performances - Barber s Adagio and Other Romantic Favorites for Strings',228)
insert into album values(295,'Carmina Burana',229)
insert into album values(296,'A Copland Celebration, Vol. I',230)
insert into album values(297,'Bach: Toccata & Fugue in D Minor',231)
insert into album values(298,'Prokofiev: Symphony No.1',232)
insert into album values(299,'Scheherazade',233)
insert into album values(300,'Bach: The Brandenburg Concertos',234)
insert into album values(301,'Chopin: Piano Concertos Nos. 1 & 2',235)
insert into album values(302,'Mascagni: Cavalleria Rusticana',236)
insert into album values(303,'Sibelius: Finlandia',237)
insert into album values(304,'Beethoven Piano Sonatas: Moonlight & Pastorale',238)
insert into album values(305,'Great Recordings of the Century - Mahler: Das Lied von der Erde',240)
insert into album values(306,'Elgar: Cello Concerto & Vaughan Williams: Fantasias',241)
insert into album values(307,'Adams, John: The Chairman Dances',242)
insert into album values(308,'Tchaikovsky: 1812 Festival Overture, Op.49, Capriccio Italien & Beethoven: Wellington s Victory',243)
insert into album values(309,'Palestrina: Missa Papae Marcelli & Allegri: Miserere',244)
insert into album values(310,'Prokofiev: Romeo & Juliet',245)
insert into album values(311,'Strauss: Waltzes',226)
insert into album values(312,'Berlioz: Symphonie Fantastique',245)
insert into album values(313,'Bizet: Carmen Highlights',246)
insert into album values(314,'English Renaissance',247)
insert into album values(315,'Handel: Music for the Royal Fireworks (Original Version 1749)',208)
insert into album values(316,'Grieg: Peer Gynt Suites & Sibelius: PellÃ©as et MÃ©lisande',248)
insert into album values(317,'Mozart Gala: Famous Arias',249)
insert into album values(318,'SCRIABIN: Vers la flamme',250)
insert into album values(319,'Armada: Music from the Courts of England and Spain',251)
insert into album values(320,'Mozart: Symphonies Nos. 40 & 41',248)
insert into album values(321,'Back to Black',252)
insert into album values(322,'Frank',252)
insert into album values(323,'Carried to Dust (Bonus Track Version)',253)
insert into album values(324,'Beethoven: Symphony No. 6  Pastoral  Etc.',254)
insert into album values(325,'Bartok: Violin & Viola Concertos',255)
insert into album values(326,'Mendelssohn: A Midsummer Night s Dream',256)
insert into album values(327,'Bach: Orchestral Suites Nos. 1 to 4',257)
insert into album values(328,'Charpentier: Divertissements, Airs & Concerts',258)
insert into album values(329,'South American Getaway',259)
insert into album values(330,'GÃ³recki: Symphony No. 3',260)
insert into album values(331,'Purcell: The Fairy Queen',261)
insert into album values(332,'The Ultimate Relexation Album',262)
insert into album values(333,'Purcell: Music for the Queen Mary',263)
insert into album values(334,'Weill: The Seven Deadly Sins',264)
insert into album values(335,'J.S. Bach: Chaconne, Suite in E Minor, Partita in E Major & Prelude, Fugue and Allegro',265)
insert into album values(336,'Prokofiev: Symphony No.5 & Stravinksy: Le Sacre Du Printemps',248)
insert into album values(337,'Szymanowski: Piano Works, Vol. 1',266)
insert into album values(338,'Nielsen: The Six Symphonies',267)
insert into album values(339,'Great Recordings of the Century: Paganini s 24 Caprices',268)
insert into album values(340,'Liszt - 12 Ã‰tudes D Execution Transcendante',269)
insert into album values(341,'Great Recordings of the Century - Shubert: Schwanengesang, 4 Lieder',270)
insert into album values(342,'Locatelli: Concertos for Violin, Strings and Continuo, Vol. 3',271)
insert into album values(343,'Respighi:Pines of Rome',226)
insert into album values(344,'Schubert: The Late String Quartets & String Quintet (3 CD s)',272)
insert into album values(345,'Monteverdi: L Orfeo',273)
insert into album values(346,'Mozart: Chamber Music',274)
insert into album values(347,'Koyaanisqatsi (Soundtrack from the Motion Picture)',275)
